spring:
  application:
    name: photo-consumer
  main:
    allow-bean-definition-overriding: true
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /

dubbo:
  scan:
    # 配置组件扫描，@Reference注解所在的包路径
    base-packages: com.dawson.consumer.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://localhost:8848
server:
  port: 8082
endpoints:
  dubbo:
    enabled: true
management:
  health:
    dubbo:
      status:
        defaults: memory
        extras: threadpool
  endpoints:
    web:
      exposure:
        include: "*"

user:
  name: "唯我成幸"