spring:
  application:
    name: photo-provider
  main:
    allow-bean-definition-overriding: true

  # 配置数据库连接池
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eladmin?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # 配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /


dubbo:
  scan:
    base-packages: com.dawson.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  provider:
    # 设置Dubbo负载均衡策略，轮询
    loadbalance: roundrobin
    # 设置全局超时
    timeout: 60000
    # 设置重试次数
    retries: 0
  registry:
    address: nacos://localhost:8848

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

#重试注解的配置项目
ptoto:
  retry:
    enable: true
    commonSystem: provider-service
    defaultUser: ricaido
    systemType: privider
    mq:

server:
  port: 8090