spring:
  application:
    name: photo-provider
  main:
    allow-bean-definition-overriding: true
dubbo:
  scan:
    base-packages: com.dawson.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  provider:
    #    设置Dubbo负载均衡策略，轮询
    loadbalance: roundrobin
  registry:
    address: nacos://localhost:8848